/**
 * Backend mirror of `shared/types/pipeline.ts`.
 *
 * The v1.0 backend tsconfig resolves `@shared/*` to `src/types/shared/*`
 * (NOT to the workspace-level `shared/types/`), so we maintain a local
 * copy of the pipeline types here. The two files must stay in sync —
 * any new export in the workspace file must be mirrored here.
 *
 * The mirror is generated by the build pipeline in v1.2; for v1.1 we
 * keep them manually in sync (this file is checked into git, not the
 * workspace file's content duplicated by a prebuild script).
 */
export type IsbnString = string;
export type PipelineStep = 1 | 2 | 3 | 4;
export type PipelineStatus = 'success' | 'partial' | 'failed';
export type StepStatus = 'success' | 'failed' | 'skipped';
export interface PipelineOptions {
  hostVoice?: string;
  guestVoice?: string;
  bgmTrack?: 'silence-1s';
  bgmVolume?: number;
  fadeInSec?: number;
  fadeOutSec?: number;
}
export interface PipelineInput {
  isbns: string[];
  options?: PipelineOptions;
}
export interface StepResult {
  step: 1 | 2 | 3 | 4;
  status: StepStatus;
  durationMs: number;
  artifact?: string;
  error?: string;
}
export interface PipelineResult {
  runId: string;
  finalMp3Path: string | null;
  downloadUrl: string | null;
  steps: StepResult[];
  status: PipelineStatus;
  totalDurationMs: number;
}
export interface ProgressEvent {
  runId: string;
  step: 1 | 2 | 3 | 4;
  percent: number;
  message: string;
  timestamp: number;
}
export type ProgressCallback = (event: ProgressEvent) => void;
export interface ScriptSegment {
  stage: 'opening' | 'intro' | 'interpret' | 'review' | 'suggest' | 'closing';
  speaker: 'host' | 'guest';
  text: string;
  emotion: '开心' | '沉思' | '激昂' | '平和' | '感慨';
  orderIndex: number;
}
export interface PipelineBookMetadata {
  isbn: string;
  title: string;
  author: string;
  coverUrl: string;
  summary: string;
  source: 'openlibrary' | 'googlebooks' | 'mock';
}
